CustomerId: int64
Surname: object
CreditScore: int64
Geography: object
Gender: object
Age: float64
Tenure: int64
Balance: float64
NumOfProducts: int64
HasCrCard: float64
IsActiveMember: float64
EstimatedSalary: float64
Exited: int64